version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.99.104:31112
functions:
  astronaut-finder:
    lang: python3
    handler: ./astronaut-finder
    image: bryanchun/astronaut-finder:latest
    environment:
      write_debug: true

